summary(iris)
head (iris)
by(iris$Petal.Length, iris$Species, summary)
mean(iris$Sepal.Length)
var(iris$Sepal.Length)
boxplot(iris$Petal.Length)
boxplot(Petal.Length ~ Species, data=iris, main="Petal Length", xlab="Species", ylab="Length")

hist(iris$Petal.Length)
hist(iris$Sepal.Width)
hist(iris$Sepal.Width[iris$Species=="setosa"])
hist(iris$Sepal.Width[iris$Species=="versicolor"])
d=density(iris$Petal.Length)
plot(d)
d=density(iris$Sepal.Width[iris$Species=="versicolor"])
plot(d)

qplot(azhar$AmountSpent, azhar$Salary)
plot (azhar$AmountSpent, azhar$Salary)
